[package]
name = "s2"
edition = "2018"

version = "0.0.10"
authors = ["Jihyun Yu <yjh0502@gmail.com>"]

license = "Apache-2.0"

description = "S2 geometric library"
homepage = "https://github.com/yjh0502/rust-s2"
repository = "https://github.com/yjh0502/rust-s2"
documentation = "https://docs.rs/rust-s2"

keywords = ["geo", "s2"]

[dependencies]
lazy_static = "1"
rand = "0.5"
cgmath = "0.16"
libm = "0.1.3"
bigdecimal = "0.1"
serde = { version = "1.0", features = ["serde_derive"], optional = true }

[profile.release]
debug = 2

[target.'cfg(feature="serde")'.dependencies]
bigdecimal = { version = "0.1", features = ["serde"] }
